_wandb:
    value:
        cli_version: 0.21.0
        e:
            a7bui2gpeo1bgrlqtn2cmoto738rp87m:
                args:
                    - C:\Tue\Master\Jaar_2\graduation\code\own_approach\run_configs\gaf_ppo_ViT_win.yaml
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1022893223936"
                        used: "938376486912"
                email: x.j.vreeswijk@student.tue.nl
                executable: C:\Users\xande\anaconda3\envs\thesis\python.exe
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-fa32d4ea-745b-861e-c8e8-4f74d68f5459
                host: LAPTOP-542U5HR9
                memory:
                    total: "16800096256"
                os: Windows-11-10.0.26100-SP0
                program: -m src.experiments.train_runner
                python: CPython 3.13.5
                root: C:\Tue\Master\Jaar_2\graduation\code\own_approach
                startedAt: "2025-08-11T10:24:48.047032Z"
                writerId: a7bui2gpeo1bgrlqtn2cmoto738rp87m
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 15
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
agent:
    value:
        adaptive_switching: true
        batch_size: 512
        buffer_size: 20000
        ent_coef: 0.018
        factor: 3
        gradient_steps: 16
        learning_rate: 5.28e-05
        learning_starts: 3600
        switch_epoch: 20
        threshold: 5
        train_freq:
            - 64
            - step
        window: 20
data:
    value:
        amp_pipeline: <src.signal_processing.pipeline.Pipeline object at 0x00000237CBABB890>
        bvp_agg: sum
        bvp_pipeline: 0
        data_dir: C:\Tue\Master\Jaar_2\graduation\code\own_approach\data
        dataset_type: single_user
        downsample_multiplier: 100
        phase_pipeline: <src.signal_processing.pipeline.Pipeline object at 0x00000237CBAD6520>
        transformation: GramianAngularField()
debug:
    value:
        is_debug: false
        offline: false
        on_cpu: false
embed:
    value:
        actor_dropout: 0.3
        actor_num_layers: 3
        agent_type: ppo
        anneal_lr: true
        clip_coef: 0.2
        clip_value_loss: true
        critic_dropout: 0.3
        critic_num_layers: 3
        embed_size: 33
        entropy_coef: 0
        epochs: 2
        gae_lambda: 0.95
        gamma: 0.99
        lr: 0.0001
        max_grad_norm: 0.5
        norm_advantage: true
        policy: exploration
        reward_function: task_performance
        start_epoch: 3
        target_kl: null
        value_func_coef: 0.5
encoder:
    value:
        Backbone_type: ViT
        activation_fn: gelu
        base_channels: 64
        dropout: 0.25
        growth_rate: 32
        init_channels: 64
        initial_kernel_size: 3
        latent_dim: 50
        layers_per_stage:
            - 2
            - 2
            - 2
            - 2
        normalization: false
        num_conv_layers: null
        patch_size: 4
        vit_depth: 4
        vit_heads: 4
mt:
    value:
        d_predictor_activation_fn: leaky
        d_predictor_dropout: 0.067
        d_predictor_num_layers: 6
        predictor_activation_fn: selu
        predictor_dropout: 0.11
        predictor_num_layers: 4
optim_loss:
    value:
        alpha: 0.000363
        beta: 0.37
        lr: 0.000629
        optimizer: adam
train:
    value:
        batch_size: 16
        checkpoint_dir: C:\Tue\Master\Jaar_2\graduation\code\own_approach\checkpoints
        epochs: 6
        tuning: false
        ui: tqdm
