_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
agent:
    value:
        batch_size: 512
        buffer_size: 50000
        ent_coef: 0.094
        factor: 2
        gradient_steps: 16
        learning_rate: 0.000312
        learning_starts: 1600
        sequential: true
        switch_epoch: 20
        threshold: 10
        train_freq:
            - 64
            - step
        window: 20
data:
    value:
        amp_pipeline: <src.signal_processing.pipeline.Pipeline object at 0x000001D9A8A193A0>
        bvp_agg: sum
        data_dir: C:\Tue\Master\Jaar_2\graduation\code\own_approach\data
        dataset_type: single_user
        downsample_multiplier: 100
        phase_pipeline: <src.signal_processing.pipeline.Pipeline object at 0x000001D9D39C11F0>
        transformation: GramianAngularField()
debug:
    value:
        is_debug: false
        offline: false
        on_cpu: false
embed:
    value:
        agent_type: sac
        embed_size: 33
        epochs: 2
        policy: do_nothing
        reward_function: combined
        start_epoch: 5
encoder:
    value:
        Backbone_type: CNN
        activation_fn: leaky
        base_channels: 128
        dropout: 0.18
        growth_rate: 32
        init_channels: 64
        initial_kernel_size: 7
        latent_dim: 60
        layers_per_stage:
            - 2
            - 2
            - 2
            - 2
        normalization: false
        num_conv_layers: null
        patch_size: 64
        vit_depth: 6
        vit_heads: 4
mt:
    value:
        d_predictor_activation_fn: gelu
        d_predictor_dropout: 0.26
        d_predictor_num_layers: 4
        predictor_activation_fn: selu
        predictor_dropout: 0.28
        predictor_num_layers: 4
optim_loss:
    value:
        alpha: 0.000255
        beta: 0.5
        lr: 0.000911
        optimizer: adam
train:
    value:
        batch_size: 32
        checkpoint_dir: ..\Checkpoints
        epochs: 100
        tuning: false
        ui: tqdm
