_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
agent:
    value:
        adaptive_switching: true
        batch_size: 512
        buffer_size: 50000
        ent_coef: 0.06401631605687026
        factor: 4
        gradient_steps: 16
        learning_rate: 7.089589902572457e-05
        learning_starts: 1600
        sequential: true
        switch_epoch: 20
        threshold: 10
        train_freq:
            - 64
            - step
        window: 20
data:
    value:
        amp_pipeline: <src.signal_processing.pipeline.Pipeline object at 0x000001BDE34275C0>
        bvp_agg: sum
        bvp_pipeline: 0
        data_dir: C:\Tue\Master\Jaar_2\graduation\code\own_approach\data
        dataset_type: single_user
        downsample_multiplier: 100
        phase_pipeline: <src.signal_processing.pipeline.Pipeline object at 0x000001BDE3640FE0>
        transformation: MarkovTransitionField()
debug:
    value:
        is_debug: false
        offline: false
        on_cpu: false
embed:
    value:
        actor_dropout: 0.3
        actor_num_layers: 3
        agent_type: sac
        anneal_lr: true
        clip_coef: 0.2
        clip_value_loss: true
        critic_dropout: 0.3
        critic_num_layers: 3
        embed_size: 33
        entropy_coef: 0
        epochs: 2
        gae_lambda: 0.95
        gamma: 0.99
        lr: 0.0001
        max_grad_norm: 0.5
        norm_advantage: true
        policy: do_nothing
        reward_function: combined
        start_epoch: 35
        target_kl: null
        value_func_coef: 0.5
        value_type: probability-measure
encoder:
    value:
        Backbone_type: DenseNet
        activation_fn: relu
        base_channels: 128
        dropout: 0.06949780642398673
        growth_rate: 56
        init_channels: 64
        initial_kernel_size: 5
        latent_dim: 30
        layers_per_stage:
            - 2
            - 2
            - 2
            - 2
        normalization: false
        num_conv_layers: null
        patch_size: 64
        vit_depth: 6
        vit_heads: 4
mt:
    value:
        d_predictor_activation_fn: relu
        d_predictor_dropout: 0.14592265699637819
        d_predictor_num_layers: 6
        predictor_activation_fn: selu
        predictor_dropout: 0.2426637792205302
        predictor_num_layers: 3
optim_loss:
    value:
        alpha: 0.00014467646280371654
        beta: 0.09646717560116949
        lr: 0.0007451656570213542
        optimizer: adam
train:
    value:
        batch_size: 32
        checkpoint_dir: \home2\xvreewij\Checkpoints
        epochs: 100
        tuning: false
        ui: tqdm
